name: Run pygbag on update

on:
  push:
    branches:
      - main

jobs:
  run-pygbag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Debug step to check SSL certificate paths
      - name: Check SSL certificates
        run: |
          python -m ssl --help  # Check SSL module for errors
          ls -al /etc/ssl/certs # List SSL certificate files
          echo | openssl s_client -showcerts -servername github.com -connect github.com:443 # Check SSL connection to GitHub

      - name: Install pygbag (no SSL verification)
        run: |
          pip install pygbag --trusted-host pypi.org --trusted-host files.pythonhosted.org


      - name: Run pygbag from parent directory
        run: |
          cd ..
          pygbag ${{ github.event.repository.name }}
